## Chapter3 Arithmetic Operators

In [1]:
3 + 1:5

[1] 4 5 6 7 8

In [2]:
5 + 2 :9

[1]  7  8  9 10 11 12 13 14

### Range operator ":" has higher precedence than "+"

In [4]:
3 + 1 :9

[1]  4  5  6  7  8  9 10 11 12

In [5]:
3 + c (1,2,3,4,5)

[1] 4 5 6 7 8

In [6]:
c(4,5,6,7,8)

[1] 4 5 6 7 8

In [8]:
# Precendence is changed with "()"
(3+ 1) :5

[1] 4 5

In [9]:
(5+ 1):4

[1] 6 5 4

In [10]:
(7+ 2) :2

[1] 9 8 7 6 5 4 3 2

In [11]:
(7+ 2) :9

[1] 9

In [12]:
3 + 4.5

[1] 7.5

In [13]:
3 + 4.5 + 2

[1] 9.5

In [14]:
3 + 4.5 + 2 - 3.9

[1] 5.6

In [15]:
3 + NA

[1] NA

In [16]:
NA + NA

[1] NA

In [17]:
Nan + NA

ERROR: Error in eval(expr, envir, enclos): object 'Nan' not found


In [18]:
NaN - NA

[1] NaN

In [19]:
NaN - NaN

[1] NaN

In [20]:
NA - NA

[1] NA

In [23]:
a <- 3; B <- 4.5; cc<- 2 ; Dd <- 3.8; na<- NA; nan <-NaN

In [24]:
a + B

[1] 7.5

In [25]:
a + B + cc

[1] 9.5

In [26]:
B- nan

[1] NaN

In [27]:
a + na- na

[1] NA

In [28]:
B- nan

[1] NaN

In [29]:
a + na -na

[1] NA

In [30]:
A <- c(3, 4.5, 2, -3.8)

In [31]:
A

[1]  3.0  4.5  2.0 -3.8

In [32]:
A + 2

[1]  5.0  6.5  4.0 -1.8

In [33]:
8 - A

[1]  5.0  3.5  6.0 11.8

In [34]:
n <- length(A)

In [35]:
n

[1] 4

In [36]:
A[-n] + A[n]

[1] -0.8  0.7 -1.8

In [37]:
A

[1]  3.0  4.5  2.0 -3.8

In [38]:
A[1:2] + 3

[1] 6.0 7.5

In [39]:
A[1:2] - A[3:4]

[1] 1.0 8.3

In [40]:
sum(A)

[1] 5.7

In [41]:
sum(-A)

[1] -5.7

In [43]:
sum(A[-n])+ A[n]

[1] 5.7

In [44]:
A[n]

[1] -3.8

In [45]:
n

[1] 4

In [46]:
sum(A[-n])

[1] 9.5

In [47]:
9.5-3.8

[1] 5.7

In [48]:
3+ 4.5+2-3.8

[1] 5.7

In [50]:
B <- c(3, 5, -3, 2.7, 1.8)

In [51]:
B

[1]  3.0  5.0 -3.0  2.7  1.8

In [52]:
A

[1]  3.0  4.5  2.0 -3.8

In [53]:
A + B

Warning message in A + B:
"longer object length is not a multiple of shorter object length"

[1]  6.0  9.5 -1.0 -1.1  4.8

In [54]:
A * B

Warning message in A * B:
"longer object length is not a multiple of shorter object length"

[1]   9.00  22.50  -6.00 -10.26   5.40

In [55]:
A - B

Warning message in A - B:
"longer object length is not a multiple of shorter object length"

[1]  0.0 -0.5  5.0 -6.5  1.2

In [56]:
B - A

Warning message in B - A:
"longer object length is not a multiple of shorter object length"

[1]  0.0  0.5 -5.0  6.5 -1.2

In [57]:
B - A

Warning message in B - A:
"longer object length is not a multiple of shorter object length"

[1]  0.0  0.5 -5.0  6.5 -1.2

In [58]:
B[1: n] + A

[1]  6.0  9.5 -1.0 -1.1

In [59]:
B [ 1: n] -A

[1]  0.0  0.5 -5.0  6.5

In [60]:
sum(A,B)

[1] 15.2

In [61]:
sum(A, -B)

[1] -3.8

In [62]:
sum(A) + sum(B)

[1] 15.2

In [63]:
sum(A,B) == (sum(A) + sum(B))

[1] TRUE

In [64]:
sum(A) - sum(B)

[1] -3.8

## Matrices Chapter- 4

In [65]:
matrix(data = 1:6, nrow = 2, ncol=3)

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [68]:
matrix(data = 1:6, nrow=2, ncol=3, byrow = TRUE)

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

In [69]:
matrix(data = 1:6, nrow=2, ncol=3)

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [73]:
matrix(data = c(TRUE, TRUE, TRUE, FALSE, FALSE, FALSE), nrow= 3, ncol=2, byrow=FALSE)

[,1] [,2] 
[1,] TRUE FALSE
[2,] TRUE FALSE
[3,] TRUE FALSE

In [75]:
matrix(data = c("a", "b", "c", "d", "e","f"), nrow = 3, ncol=2, byrow=TRUE)

[,1] [,2]
[1,] a    b   
[2,] c    d   
[3,] e    f

In [76]:
mat1 <- matrix(data = 1:6, nrow = 2, ncol =3, byrow=TRUE)

In [77]:
mat1

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

In [78]:
rownames(mat1)

NULL

In [79]:
colnames(mat1)

NULL

In [80]:
rownames(mat1) <- c("Row 1", "Row 2")

In [81]:
rownames(mat1)

[1] "Row 1" "Row 2"

In [82]:
colnames(mat1)

NULL

In [84]:
colnames(mat1) <- c("Col 1", "Col 2", "Col 3")

In [85]:
colnames(mat1)

[1] "Col 1" "Col 2" "Col 3"

In [86]:
mat1

Col 1 Col 2 Col 3
Row 1 1     2     3    
Row 2 4     5     6

In [87]:
class(mat1)

[1] "matrix"

In [88]:
is.matrix(mat1)

[1] TRUE

In [89]:
as.vector(mat1)

[1] 1 4 2 5 3 6

## Chapter-5 FORMULA

In [92]:
my_formula1 <- formula (mpg ~ wt)

In [93]:
class(my_formula1)

[1] "formula"

mod1 <- lm(my_formula1, data = mtcars)

In [94]:
mod1 <- lm(my_formula1, data = mtcars)

In [95]:
coef(mod1)

(Intercept)          wt 
  37.285126   -5.344472

In [96]:
help(lm)

In [97]:
form <- mpg ~ wt

In [98]:
class(form)

[1] "formula"

In [99]:
form_wt <- formula(mpg ~ wt, env = mtcars)

In [100]:
class(form_wt)

[1] "formula"

In [101]:
coef(lm(mpg ~ 0 + wt, data=mtcars))

wt 
5.291624

In [102]:
coef(lm(mpg ~ wt - 1, data =mtcars))

wt 
5.291624

In [103]:
coef(lm(mpg ~ wt:vs, data = mtcars))

(Intercept)       wt:vs 
  17.805937    1.999836

In [104]:
coef(lm(mpg ~ wt *vs, data =mtcars))

(Intercept)          wt          vs       wt:vs 
  29.531444   -3.501310   11.766696   -2.909707

In [105]:
# include all lower order terms
coef(lm(mpg ~ wt *vs*hp, data =mtcars))

(Intercept)          wt          vs          hp       wt:vs       wt:hp 
46.34789353 -7.68255426 -4.54377141 -0.10291333  3.92910670  0.02509225 
      vs:hp    wt:vs:hp 
 0.05489371 -0.03744986

In [106]:
coef(lm(mpg ~ wt*vs*hp - wt:vs:hp, data =mtcars))

(Intercept)          wt          vs          hp       wt:vs       wt:hp 
43.07158105 -6.62103249  5.94975993 -0.08537686 -0.18320956  0.01960329 
      vs:hp 
-0.04103392

In [107]:
coef(lm(mpg ~ (wt + vs + hp) ^ 2, data = mtcars))

(Intercept)          wt          vs          hp       wt:vs       wt:hp 
43.07158105 -6.62103249  5.94975993 -0.08537686 -0.18320956  0.01960329 
      vs:hp 
-0.04103392

In [108]:
coef(lm(mpg ~., data = mtcars))

(Intercept)         cyl        disp          hp        drat          wt 
12.30337416 -0.11144048  0.01333524 -0.02148212  0.78711097 -3.71530393 
       qsec          vs          am        gear        carb 
 0.82104075  0.31776281  2.52022689  0.65541302 -0.19941925

## Chapter-6 ......READING WRITING STRINGS

In [109]:
print("Hello World")

[1] "Hello World"


In [110]:
cat("Hello World")

Hello World

In [111]:
cat(c("Hello", "World", "\n"))

Hello World 


In [112]:
print(c("Hello", "world", "\n"))

[1] "Hello" "world" "\n"   


In [115]:
cat("Hello", "World")

Hello World

In [116]:
print("Hello World")

[1] "Hello World"


In [117]:
s <- "Hello World"

In [118]:
s

[1] "Hello World"

In [119]:
print(s)

[1] "Hello World"


In [120]:
cat(s)

Hello World

In [121]:
print(s) == cat(s)

[1] "Hello World"
Hello World

logical(0)

In [122]:
"Hello World"

[1] "Hello World"

In [123]:
print(c("Hello World", "Here I am"))

[1] "Hello World" "Here I am"  


In [124]:
c("Hello", "Shashi", "Africa", "I am")

[1] "Hello"  "Shashi" "Africa" "I am"

In [125]:
print(1)

[1] 1


In [126]:
print(TRUE)

[1] TRUE


### REPL (Read-eval-print-loop)

## The above is comment

In [128]:
message("Hello World")

Hello World


In [130]:
suppressMessages(message("hello world"))

message("hello world")

In [131]:
system("top -a -b -n 1", intern = TRUE)

ERROR: Error in system("top -a -b -n 1", intern = TRUE): 'top' not found


In [132]:
line <- readLines(conn, n=1, warn =FALSE)

ERROR: Error in readLines(conn, n = 1, warn = FALSE): object 'conn' not found
