## Chap-2 Variables

# R-Programming

In [1]:
list('.11'="a")

$`.11`
[1] "a"

In [2]:
a

ERROR: Error in eval(expr, envir, enclos): object 'a' not found


In [3]:
.11

[1] 0.11

In [4]:
'.11'

[1] ".11"

In [5]:
$'.11'

ERROR: Error in parse(text = x, srcfile = src): <text>:1:1: unexpected '$'
1: $
    ^


In [6]:
foo <-43

In [7]:
fooEquals=43

In [8]:
foo

[1] 43

In [9]:
fooEquals

[1] 43

In [10]:
(x<-5)

[1] 5

In [11]:
is.function('(')

[1] FALSE

In [12]:
5 ->x

In [13]:
x

[1] 5

In [14]:
5

[1] 5

In [15]:
v <- c(2, 3, 7, 10)

In [16]:
v

[1]  2  3  7 10

In [17]:
v2 <- c("a", "b", "c")

In [18]:
v2

[1] "a" "b" "c"

In [22]:
a<-matrix(data=c(1,2,3,4,5,6,7,8,9,10,11,12), nrow=3, ncol=4, byrow=F)

In [23]:
a

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

In [24]:
mylist <- list (course = 'stat', date = '04/07/2009',
num_isc = 7, num_cons = 6, num_mat = as.character(c(45020, 45679, 46789, 43126, 42345, 47568,
45674)), results = c(30, 19, 29, NA, 25, 26 ,27))

In [25]:
mylist

$course
[1] "stat"

$date
[1] "04/07/2009"

$num_isc
[1] 7

$num_cons
[1] 6

$num_mat
[1] "45020" "45679" "46789" "43126" "42345" "47568" "45674"

$results
[1] 30 19 29 NA 25 26 27

In [26]:
exam <- data.frame(matr = as.character(c(45020, 45679, 46789, 43126, 42345, 47568,
45674)), res_S = c(30, 19, 29, NA, 25, 26, 27), res_O = c(3, 3, 1, NA, 3, 2, NA), res_TOT =
c(30,22,30,NA,28,28,27))

In [27]:
exam

matr  res_S res_O res_TOT
1 45020 30     3    30     
2 45679 19     3    22     
3 46789 29     1    30     
4 43126 NA    NA    NA     
5 42345 25     3    28     
6 47568 26     2    28     
7 45674 27    NA    27

In [28]:
a <- 1

In [29]:
b<-2

In [30]:
c<-4

In [31]:
c<-c(2,3,4)

In [32]:
c

[1] 2 3 4

In [33]:
d<-c(10,10,10)

In [34]:
d

[1] 10 10 10

In [35]:
f<-1:6

In [36]:
f

[1] 1 2 3 4 5 6

In [37]:
W<-cbind(1:4, 5:8, 9:12)

In [38]:
W

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

In [43]:
Z<-rbind(rep('A',3), 1:3, rep('B',3), c(4,7,1))

In [44]:
Z

[,1] [,2] [,3]
[1,] A    A    A   
[2,] 1    2    3   
[3,] B    B    B   
[4,] 4    7    1

In [45]:
a + b

[1] 3

In [46]:
c + d

[1] 12 13 14

In [47]:
W + Z

ERROR: Error in W + Z: non-numeric argument to binary operator


In [48]:
c*d

[1] 20 30 40

In [49]:
exp(c)

[1]  7.389056 20.085537 54.598150

In [50]:
c+e

ERROR: Error in eval(expr, envir, enclos): object 'e' not found


In [51]:
Z+W

ERROR: Error in Z + W: non-numeric argument to binary operator


In [52]:
Z*W

ERROR: Error in Z * W: non-numeric argument to binary operator


In [53]:
W+a

[,1] [,2] [,3]
[1,] 2    6    10  
[2,] 3    7    11  
[3,] 4    8    12  
[4,] 5    9    13

In [54]:
W+c

[,1] [,2] [,3]
[1,] 3     8   13  
[2,] 5    10   12  
[3,] 7     9   14  
[4,] 6    11   16

In [55]:
foo <- 'foo'

In [56]:
foo

[1] "foo"

In [57]:
.foo<-'bar'

In [58]:
.foo

[1] "bar"

In [59]:
ls(all.names=TRUE)

[1] ".foo"      ".pbd_env"  "a"         "b"         "c"         "d"        
 [7] "exam"      "f"         "foo"       "fooEquals" "mylist"    "v"        
[13] "v2"        "W"         "x"         "Z"

In [60]:
ls()

[1] "a"         "b"         "c"         "d"         "exam"      "f"        
 [7] "foo"       "fooEquals" "mylist"    "v"         "v2"        "W"        
[13] "x"         "Z"

In [61]:
ls(all.names=TRUE)

[1] ".foo"      ".pbd_env"  "a"         "b"         "c"         "d"        
 [7] "exam"      "f"         "foo"       "fooEquals" "mylist"    "v"        
[13] "v2"        "W"         "x"         "Z"

## Arithmetic Operators

In [62]:
3 + 1:5

[1] 4 5 6 7 8

In [63]:
## 'Range' operator higher precedence than '+'

In [64]:
3+1:5

[1] 4 5 6 7 8

In [65]:
3+c(1,2,3,4,5)

[1] 4 5 6 7 8

In [66]:
3+1:5 == 3+c(1,2,3,4,5)

[1] TRUE TRUE TRUE TRUE TRUE

In [67]:
c(4,5,6,7,8)

[1] 4 5 6 7 8

In [68]:
(3+1):5

[1] 4 5

In [69]:
3+ 4.5

[1] 7.5

In [70]:
3+4.5+2

[1] 9.5

In [71]:
3+4.5+2-3.8

[1] 5.7

In [72]:
3 + NA

[1] NA

In [73]:
NA+NA

[1] NA

In [74]:
NA-NA

[1] NA

In [75]:
NaN-NA

[1] NaN

In [76]:
NaN+NA

[1] NaN

In [79]:
a <- 3; B<-4.5; cc<-2; Dd<- 3.8; na<-NA; nan<-NaN

In [80]:
ls()

[1] "a"         "b"         "B"         "c"         "cc"        "d"        
 [7] "Dd"        "exam"      "f"         "foo"       "fooEquals" "mylist"   
[13] "na"        "nan"       "v"         "v2"        "W"         "x"        
[19] "Z"

In [81]:
a

[1] 3

In [82]:
B

[1] 4.5

In [83]:
cc

[1] 2

In [84]:
Dd

[1] 3.8

In [85]:
a + B

[1] 7.5

In [86]:
a+B+Dd

[1] 11.3

In [87]:
a+B+cc

[1] 9.5

In [89]:
a+B+cc-Dd

[1] 5.7

In [90]:
a+na-na

[1] NA

In [91]:
B-nan

[1] NaN

### 

In [92]:
A<-c(3,4.5,2,-3.8)

In [93]:
A

[1]  3.0  4.5  2.0 -3.8

In [94]:
A+2

[1]  5.0  6.5  4.0 -1.8

In [95]:
8-A

[1]  5.0  3.5  6.0 11.8

In [96]:
n<-length(A)

In [97]:
n

[1] 4

In [98]:
A[-n]+A[n]

[1] -0.8  0.7 -1.8

In [99]:
A[-n]

[1] 3.0 4.5 2.0

In [100]:
A

[1]  3.0  4.5  2.0 -3.8

In [101]:
A[1:2]

[1] 3.0 4.5

In [102]:
A[1:2]+3

[1] 6.0 7.5

In [103]:
A[1:2]-A[3:4]

[1] 1.0 8.3

In [104]:
sum(A)

[1] 5.7

In [105]:
su(-A)

ERROR: Error in su(-A): could not find function "su"


In [106]:
sum(-A)

[1] -5.7

In [108]:
sum(A[-n])+A[n]

[1] 5.7

In [109]:
B<-c(3,5,-3,2.7,1.8)

In [110]:
B

[1]  3.0  5.0 -3.0  2.7  1.8

In [111]:
A

[1]  3.0  4.5  2.0 -3.8

In [112]:
A + B

Warning message in A + B:
"longer object length is not a multiple of shorter object length"

[1]  6.0  9.5 -1.0 -1.1  4.8

In [113]:
B- A

Warning message in B - A:
"longer object length is not a multiple of shorter object length"

[1]  0.0  0.5 -5.0  6.5 -1.2

In [114]:
B * A

Warning message in B * A:
"longer object length is not a multiple of shorter object length"

[1]   9.00  22.50  -6.00 -10.26   5.40

In [115]:
B /A

Warning message in B/A:
"longer object length is not a multiple of shorter object length"

[1]  1.0000000  1.1111111 -1.5000000 -0.7105263  0.6000000

In [116]:
B[1:n] + A

[1]  6.0  9.5 -1.0 -1.1

In [117]:
B[1:n] -A

[1]  0.0  0.5 -5.0  6.5

In [118]:
sum(A,B)

[1] 15.2

In [119]:
sum(A,-B)

[1] -3.8

In [120]:
sum(A) + sum(B)

[1] 15.2

In [121]:
sum(A) - sum(B)

[1] -3.8

## Matrices

In [124]:
matrix(data=1:6, nrow=2, ncol=3)

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

matrix(data=1:6, nrow=2, ncol=3, byrow=TRUE)

In [125]:
matrix(data=1:6, nrow=2, ncol=3, byrow=TRUE)

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

In [129]:
matrix(data = c(TRUE, TRUE, TRUE, FALSE, FALSE, FALSE), nrow = 3, ncol = 15)

Warning message in matrix(data = c(TRUE, TRUE, TRUE, FALSE, FALSE, FALSE), nrow = 3, :
"data length [6] is not a sub-multiple or multiple of the number of columns [15]"

[,1] [,2]  [,3] [,4]  [,5] [,6]  [,7] [,8]  [,9] [,10] [,11] [,12] [,13]
[1,] TRUE FALSE TRUE FALSE TRUE FALSE TRUE FALSE TRUE FALSE TRUE  FALSE TRUE 
[2,] TRUE FALSE TRUE FALSE TRUE FALSE TRUE FALSE TRUE FALSE TRUE  FALSE TRUE 
[3,] TRUE FALSE TRUE FALSE TRUE FALSE TRUE FALSE TRUE FALSE TRUE  FALSE TRUE 
     [,14] [,15]
[1,] FALSE TRUE 
[2,] FALSE TRUE 
[3,] FALSE TRUE

In [127]:
matrix(data = c("a", "b", "c", "d", "e", "f"), nrow = 3, ncol = 2)

[,1] [,2]
[1,] a    d   
[2,] b    e   
[3,] c    f

In [130]:
mat1<-matrix(data=1:6, nrow=2, ncol=3, byrow=TRUE)

In [131]:
mat1

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

In [132]:
rownames(mat1)

NULL

In [133]:
colnames(mat1)

NULL

In [134]:
rownames(mat1) <-c("Row1", "Row2")

In [136]:
colnames(mat1)<-c("Col1", "Col2", "Col3")

# 

mat1

In [137]:
mat1

Col1 Col2 Col3
Row1 1    2    3   
Row2 4    5    6

In [138]:
class(mat1)

[1] "matrix"

In [139]:
is.matrix(mat1)

[1] TRUE

In [140]:
as.vector(mat1)

[1] 1 4 2 5 3 6

## Chap-5 FORMULA

In [141]:
my_formula1 <-formula(mpg ~ wt)

In [142]:
my_formula1

mpg ~ wt

In [143]:
class(my_formula1)

[1] "formula"

In [145]:
mod1<-lm(my_formula1, data=mtcars)

mod1

In [146]:
mod1


Call:
lm(formula = my_formula1, data = mtcars)

Coefficients:
(Intercept)           wt  
     37.285       -5.344  


In [147]:
form <- mpg ~wt

In [148]:
class(form)

[1] "formula"

In [149]:
form_wt <- formula(mpg ~ wt, env=mtcars)

In [150]:
form_wt

mpg ~ wt

In [152]:
coef(lm(mpg ~ 0 +wt, data=mtcars))

wt 
5.291624

In [153]:
coef(lm(mpg~wt:vs, data=mtcars))

(Intercept)       wt:vs 
  17.805937    1.999836

In [154]:
coef(lm(mpg ~ wt:vs, data = mtcars))

(Intercept)       wt:vs 
  17.805937    1.999836

In [155]:
coef(lm(mpg ~ wt*vs, data = mtcars))

(Intercept)          wt          vs       wt:vs 
  29.531444   -3.501310   11.766696   -2.909707

In [156]:
coef(lm(mpg ~ wt*vs*hp, data = mtcars))

(Intercept)          wt          vs          hp       wt:vs       wt:hp 
46.34789353 -7.68255426 -4.54377141 -0.10291333  3.92910670  0.02509225 
      vs:hp    wt:vs:hp 
 0.05489371 -0.03744986

In [157]:
coef(lm(mpg ~(wt+vs+hp)^2, data=mtcars))

(Intercept)          wt          vs          hp       wt:vs       wt:hp 
43.07158105 -6.62103249  5.94975993 -0.08537686 -0.18320956  0.01960329 
      vs:hp 
-0.04103392

## Chap-6 Reading and Writing Strings

In [163]:
print("Hello World\n MY name is Shashi")

[1] "Hello World\n MY name is Shashi"


In [159]:
cat("Hellow World\n")

Hellow World


In [160]:
cat(c("Hello", "World", "\n"))

Hello World 


In [161]:
cat("Hello World")

Hello World

In [164]:
s <- "Hello World"

In [165]:
s

[1] "Hello World"

In [166]:
print(c("Hello world", "I am here","\n"))

[1] "Hello world" "I am here"   "\n"         


In [168]:
c("Hello World", "I am here", "This is what i expect This next string is really long")

[1] "Hello World"                                          
[2] "I am here"                                            
[3] "This is what i expect This next string is really long"

In [172]:
print(1)+print("shash")

[1] 1
[1] "shash"


ERROR: Error in print(1) + print("shash"): non-numeric argument to binary operator


In [170]:
print(TRUE)

[1] TRUE


In [171]:
print("shash")

[1] "shash"


## R console is REPL(Read-eval-print-loop)

In [173]:
message("Hello world")

Hello world


In [174]:
suppressMessages(message("hello world"))

In [176]:
#Works in Linux systems
system("top -a -b -n 1", intern = TRUE)

ERROR: Error in system("top -a -b -n 1", intern = TRUE): 'top' not found


## Chap.7 String Manipulation with "stringi"

In [177]:
stri_count_fixed("babab","b")

ERROR: Error in stri_count_fixed("babab", "b"): could not find function "stri_count_fixed"


In [178]:
stri_count_fixed("babab", "b")

ERROR: Error in stri_count_fixed("babab", "b"): could not find function "stri_count_fixed"


In [179]:
length(gregexpr("b","babab")[[1]])

[1] 3

In [180]:
length(gregexpr("ba","babab")[[1]])

[1] 2

In [181]:
length(gregexpr("bab","babab")[[1]])

[1] 1

In [182]:
sapply(c("b","ba"),function(x)length(gregexpr(x,"babab")[[1]]))

b ba 
 3  2

In [183]:
stri_dup("abc", 3)

ERROR: Error in stri_dup("abc", 3): could not find function "stri_dup"


In [184]:
paste0(rep("abc",3),collapse = "")

[1] "abcabcabc"

In [185]:
stri_paste(LETTERS,"-", 1:13)

ERROR: Error in stri_paste(LETTERS, "-", 1:13): could not find function "stri_paste"


# Chap-8 Classes

In [186]:
class(iris)

[1] "data.frame"

In [187]:
str(iris)

'data.frame':	150 obs. of  5 variables:
 $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
 $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
 $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
 $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
 $ Species     : Factor w/ 3 levels "setosa","versicolor",..: 1 1 1 1 1 1 1 1 1 1 ...


In [188]:
class(iris$Species)

[1] "factor"

In [189]:
ls()

[1] "a"           "A"           "b"           "B"           "c"          
 [6] "cc"          "d"           "Dd"          "exam"        "f"          
[11] "foo"         "fooEquals"   "form"        "form_wt"     "mat1"       
[16] "mod1"        "my_formula1" "mylist"      "n"           "na"         
[21] "nan"         "s"           "v"           "v2"          "W"          
[26] "x"           "Z"

In [190]:
class(form_wt)

[1] "formula"

In [191]:
class(W)

[1] "matrix"

In [192]:
class(f)

[1] "integer"

In [193]:
class(foo)

[1] "character"

In [194]:
class(nan)

[1] "numeric"

In [195]:
class(na)

[1] "logical"

In [196]:
str(iris)

'data.frame':	150 obs. of  5 variables:
 $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
 $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
 $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
 $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
 $ Species     : Factor w/ 3 levels "setosa","versicolor",..: 1 1 1 1 1 1 1 1 1 1 ...


In [197]:
x <- 1826

In [198]:
x

[1] 1826

In [199]:
x<-as.Date("1970-01-01")

In [200]:
x

[1] "1970-01-01"

In [201]:
class(x)

[1] "Date"

In [202]:
is(x,"Date")

[1] TRUE

In [203]:
is(x,"integer")

[1] FALSE

In [204]:
is(x,"numeric")

[1] FALSE

In [205]:
mode(x)

[1] "numeric"

In [207]:
mylist<- list(A=c(5,6,7,8), B=letters[1:10], CC=list(5,"Z"))

In [208]:
mylist

$A
[1] 5 6 7 8

$B
 [1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j"

$CC
$CC[[1]]
[1] 5

$CC[[2]]
[1] "Z"

In [209]:
f<- function(x) list(xplus = x + 10, xsq=x^2)

In [210]:
f

function(x) list(xplus = x + 10, xsq=x^2)

In [211]:
f(7)

$xplus
[1] 17

$xsq
[1] 49

In [212]:
L <- list(x = 1:2, y = c("A","B"))
DF <- data.frame(L)
DF

x y
1 1 A
2 2 B

In [213]:
is.list(DF)

[1] TRUE

In [214]:
c(1,2,3)

[1] 1 2 3

In [215]:
c(TRUE, TRUE, FALSE)

[1]  TRUE  TRUE FALSE

In [216]:
c("a", "b", "c")

[1] "a" "b" "c"

In [217]:
x <- c(1, 2, 5)
y <- c(3, 4, 6)
z <- c(x, y)
z

[1] 1 2 5 3 4 6

In [218]:
sort(z)

[1] 1 2 3 4 5 6

### Lists

In [220]:
l1<-list(c(1,2,3), c("a","b","c"))

In [221]:
l1

[[1]]
[1] 1 2 3

[[2]]
[1] "a" "b" "c"

In [222]:
names(l1)

NULL

In [223]:
l1[0]

list()

In [224]:
l1

[[1]]
[1] 1 2 3

[[2]]
[1] "a" "b" "c"

In [225]:
print(l1)

[[1]]
[1] 1 2 3

[[2]]
[1] "a" "b" "c"



In [226]:
l1[0][1]

[[1]]
NULL

In [227]:
names(l1)<-c("vector1", "vector2")

In [239]:
l1[[1]]

[1] 1 2 3

In [229]:
l2<-list(vec=c(1,3,5,7,9), mat=matrix(data=c(1,2,3), nrow=3))

In [230]:
l2

$vec
[1] 1 3 5 7 9

$mat
     [,1]
[1,]    1
[2,]    2
[3,]    3

In [231]:
exampleList1<-list('a','b')

In [232]:
exampleList2<-list(1,2)

In [233]:
exampleList3<-list('a',1,2)

In [234]:
str(exampleList1)

List of 2
 $ : chr "a"
 $ : chr "b"


In [235]:
str(exampleList2)

List of 2
 $ : num 1
 $ : num 2


In [236]:
str(exampleList3)

List of 3
 $ : chr "a"
 $ : num 1
 $ : num 2


In [237]:
exampleList1[1]

[[1]]
[1] "a"

In [238]:
exampleList1[1:2]

[[1]]
[1] "a"

[[2]]
[1] "b"

In [240]:
exampleList1[[0]]

ERROR: Error in exampleList1[[0]]: attempt to select less than one element in get1index <real>


In [242]:
exampleList1[[2]]

[1] "b"

In [243]:
exampleList1[[3]]

ERROR: Error in exampleList1[[3]]: subscript out of bounds


In [245]:
exampleList4<-list(num=1:3, numeric=0.5, char=c('a','b'))

In [246]:
exampleList4[['char']]

[1] "a" "b"

In [247]:
exampleList4

$num
[1] 1 2 3

$numeric
[1] 0.5

$char
[1] "a" "b"

In [248]:
exampleList4$num

[1] 1 2 3

In [249]:
exampleList4$char

[1] "a" "b"

In [250]:
exampleList4$numeric

[1] 0.5

In [251]:
exampleList5<-exampleList4[2:3]

In [253]:
exampleList4$num

[1] 1 2 3

In [254]:
exampleList5$num

[1] 0.5

In [255]:
exampleList5[['num']]

NULL

In [256]:
exampleVector1<-c(12,13,14)

In [257]:
exampleVector1

[1] 12 13 14

In [258]:
exampleVector2 <-c("a","b","c","d","e","f")

In [259]:
exampleMatrix1<-matrix(rnorm(4), ncol=2, nrow=2)

In [260]:
exampleList3<-list('a',1,2)

In [261]:
exampleList3

[[1]]
[1] "a"

[[2]]
[1] 1

[[3]]
[1] 2

In [262]:
exampleList6<-list(num=exampleVector1, char=exampleVector2, mat=exampleMatrix1, list=exampleList3)

In [264]:
exampleList6

$num
[1] 12 13 14

$char
[1] "a" "b" "c" "d" "e" "f"

$mat
           [,1]      [,2]
[1,] -0.3900473 1.3039266
[2,]  2.1971917 0.2540306

$list
$list[[1]]
[1] "a"

$list[[2]]
[1] 1

$list[[3]]
[1] 2

In [265]:
df

function (x, df1, df2, ncp, log = FALSE) 
{
    if (missing(ncp)) 
        .Call(C_df, x, df1, df2, log)
    else .Call(C_dnf, x, df1, df2, ncp, log)
}
<bytecode: 0x000000000524f8e8>
<environment: namespace:stats>

In [266]:
number<-"43"

In [267]:
number

[1] "43"

In [268]:
H<-new.env(hash=TRUE)

In [269]:
H

<environment: 0x0000000005d163d0>

## Chapter 10: Hashmaps

In [270]:
H<-new.env(hash=TRUE)

In [271]:
H

<environment: 0x0000000004571f60>

In [272]:
H<-new.env()

In [273]:
H

<environment: 0x0000000004fa3848>

In [274]:
object.size(new.env())

56 bytes

In [275]:
object.size(new.env(size=10e4))

56 bytes

In [276]:
H<-new.env()

In [277]:
H[["key"]]<-rnorm(1)

In [278]:
key2<-"xyz"

In [279]:
H[[key2]]<- data.frame(x=1:3, y=letters[1:3])

In [280]:
H

<environment: 0x00000000566346e0>

In [281]:
H[[1]]

ERROR: Error in H[[1]]: wrong arguments for subsetting an environment


In [282]:
H[[key2]]

x y
1 1 a
2 2 b
3 3 c

In [283]:
H[[key2[[1]]]]

x y
1 1 a
2 2 b
3 3 c

In [284]:
H$another_key <- matrix(rbinom(9, 1, 0.5) > 0, nrow = 3)

In [287]:
H["error"]<-43

ERROR: Error in H["error"] <- 43: object of type 'environment' is not subsettable


In [288]:
H[["key3"]] <- "original value"
H[["key3"]] <- "new value"
H[["key3"]]

[1] "new value"

In [289]:
H[["key"]]

[1] -0.3629689

In [290]:
H[[key2]]

x y
1 1 a
2 2 b
3 3 c

In [291]:
H$another_key

[,1]  [,2]  [,3] 
[1,] FALSE  TRUE FALSE
[2,]  TRUE FALSE  TRUE
[3,]  TRUE FALSE  TRUE

In [292]:
H$another_key

[,1]  [,2]  [,3] 
[1,] FALSE  TRUE FALSE
[2,]  TRUE FALSE  TRUE
[3,]  TRUE FALSE  TRUE

In [293]:
names(H)

[1] "another_key" "xyz"         "key"         "key3"

In [294]:
str(H)

<environment: 0x00000000566346e0> 


In [295]:
ls.str(H)

another_key :  logi [1:3, 1:3] FALSE TRUE TRUE TRUE FALSE FALSE ...
key :  num -0.363
key3 :  chr "new value"
xyz : 'data.frame':	3 obs. of  2 variables:
 $ x: int  1 2 3
 $ y: Factor w/ 3 levels "a","b","c": 1 2 3

In [296]:
rm(list=c("key", "key3"), envir=H)

In [297]:
ls.str(H)

another_key :  logi [1:3, 1:3] FALSE TRUE TRUE TRUE FALSE FALSE ...
xyz : 'data.frame':	3 obs. of  2 variables:
 $ x: int  1 2 3
 $ y: Factor w/ 3 levels "a","b","c": 1 2 3

In [298]:
H2<-new.env()

In [299]:
H2

<environment: 0x000000000490c218>

In [300]:
H2[["a"]] <- LETTERS
H2[["b"]] <- as.list(x = 1:5, y = matrix(rnorm(10), 2))
H2[["c"]] <- head(mtcars, 3)
H2[["d"]] <- Sys.Date()
H2[["e"]] <- Sys.time()
H2[["f"]] <- (function() {
H3 <- new.env()
for (i in seq_along(names(H2))) {
H3[[names(H2)[i]]] <- H2[[names(H2)[i]]]
}
H3
})()

In [301]:
ls.str(H2)

a :  chr [1:26] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" ...
b : List of 5
 $ : int 1
 $ : int 2
 $ : int 3
 $ : int 4
 $ : int 5
c : 'data.frame':	3 obs. of  11 variables:
 $ mpg : num  21 21 22.8
 $ cyl : num  6 6 4
 $ disp: num  160 160 108
 $ hp  : num  110 110 93
 $ drat: num  3.9 3.9 3.85
 $ wt  : num  2.62 2.88 2.32
 $ qsec: num  16.5 17 18.6
 $ vs  : num  0 0 1
 $ am  : num  1 1 1
 $ gear: num  4 4 4
 $ carb: num  4 4 1
d :  Date[1:1], format: "2020-09-13"
e :  POSIXct[1:1], format: "2020-09-13 18:34:34"
f : <environment: 0x0000000005534a00> 

In [302]:
ls.str(H2$f)

a :  chr [1:26] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" ...
b : List of 5
 $ : int 1
 $ : int 2
 $ : int 3
 $ : int 4
 $ : int 5
c : 'data.frame':	3 obs. of  11 variables:
 $ mpg : num  21 21 22.8
 $ cyl : num  6 6 4
 $ disp: num  160 160 108
 $ hp  : num  110 110 93
 $ drat: num  3.9 3.9 3.85
 $ wt  : num  2.62 2.88 2.32
 $ qsec: num  16.5 17 18.6
 $ vs  : num  0 0 1
 $ am  : num  1 1 1
 $ gear: num  4 4 4
 $ carb: num  4 4 1
d :  Date[1:1], format: "2020-09-13"
e :  POSIXct[1:1], format: "2020-09-13 18:34:34"

In [303]:
names(H2)

[1] "a" "b" "c" "d" "e" "f"

In [304]:
H2[[c("a","b")]]

ERROR: Error in H2[[c("a", "b")]]: wrong arguments for subsetting an environment


In [305]:
keys<-c("a","b")

In [307]:
H2[[keys]]

ERROR: Error in H2[[keys]]: wrong arguments for subsetting an environment


In [308]:
E1 <- new.env()
invisible({
vapply(letters, function(x) {
E1[[x]] <- rnorm(1)
logical(0)
}, FUN.VALUE = logical(0))
})
all.equal(sort(names(E1)), letters)

[1] TRUE

In [309]:
Keys <- letters
E2 <- list2env(
setNames(
as.list(rnorm(26)),
nm = Keys),
envir = NULL,
hash = TRUE
)
all.equal(sort(names(E2)), letters)

[1] TRUE

In [310]:
# Generic unique string generator
unique_strings <- function(n){
string_i <- 1
string_len <- 1
ans <- character(n)
chars <- c(letters,LETTERS)
new_strings <- function(len,pfx){
for(i in 1:length(chars)){
if (len == 1){
ans[string_i] <<- paste(pfx,chars[i],sep='')
string_i <<- string_i + 1
} else {
new_strings(len-1,pfx=paste(pfx,chars[i],sep=''))
}
if (string_i > n) return ()
}
}
while(string_i <= n){
new_strings(string_len,'')
string_len <- string_len + 1
}
sample(ans)
}
# Generate timings using an enviornment
timingsEnv <- plyr::adply(2^(10:15),.mar=1,.fun=function(i){
strings <- unique_strings(i)
ht1 <- new.env(hash=TRUE)
lapply(strings, function(s){ ht1[[s]] <<- 0L})
data.frame(
size=c(i,i),
seconds=c(
system.time(for (j in 1:i) ht1[[strings[j]]]==0L)[3]),
type = c('1_hashedEnv')
)
})
timingsHash <- plyr::adply(2^(10:15),.mar=1,.fun=function(i){
strings <- unique_strings(i)
ht <- hash::hash()
lapply(strings, function(s) ht[[s]] <<- 0L)
data.frame(
size=c(i,i),
seconds=c(
system.time(for (j in 1:i) ht[[strings[j]]]==0L)[3]),
type = c('3_stringHash')
)
})

Warning message in data.frame(size = c(i, i), seconds = c(system.time(for (j in 1:i) ht1[[strings[j]]] == :
"row names were found from a short variable and have been discarded"Warning message in data.frame(size = c(i, i), seconds = c(system.time(for (j in 1:i) ht1[[strings[j]]] == :
"row names were found from a short variable and have been discarded"Warning message in data.frame(size = c(i, i), seconds = c(system.time(for (j in 1:i) ht1[[strings[j]]] == :
"row names were found from a short variable and have been discarded"Warning message in data.frame(size = c(i, i), seconds = c(system.time(for (j in 1:i) ht1[[strings[j]]] == :
"row names were found from a short variable and have been discarded"Warning message in data.frame(size = c(i, i), seconds = c(system.time(for (j in 1:i) ht1[[strings[j]]] == :
"row names were found from a short variable and have been discarded"Warning message in data.frame(size = c(i, i), seconds = c(system.time(for (j in 1:i) ht1[[strings[j]]] == :
"row names w

ERROR: Error in loadNamespace(name): there is no package called 'hash'


In [311]:
timingsListEnv <- plyr::adply(2^(10:15),.mar=1,.fun=function(i){
strings <- unique_strings(i)
le <- listenv::listenv()
lapply(strings, function(s) le[[s]] <<- 0L)
data.frame(
size=c(i,i),
seconds=c(
system.time(for (k in 1:i) le[[k]]==0L)[3]),
type = c('2_numericListEnv')
)
})

ERROR: Error in loadNamespace(name): there is no package called 'listenv'
